appName: jmail
# Jeopardy mailbox account
account: ''
# Google app password
password: ''
# Google form URL
form_url: ''

games:
  - name: ''
    # List of players' emails.
    recipients:
      - name: ''
        email: ''

    # Google Sheets URL for scoreboard.
    sheet:
      url: ''

  - name: ''
    recipients:
      - name: ''
        email: ''

    # Google Sheets URL for scoreboard.
    sheet:
      url: ''
